name: lorangerie-test
favicon: null
layout_spectrum: 1
typography_spectrum: 0.36663
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdbc3c'
    - '#f4ede7'
    - '#ab7547'
    - '#22221d'
    - '#2bac57'
  brandStrength: 0.625
  lightness: 0.8847512751817703
  saturation: 0.4375
  rhythmicContrast: 0.9221303039230406
purpose: []
